export const exampleExitQuestionnaire = {
  type: "exit",
  sections: [
    {
      instructions:
        "For each statement, please indicate how much you agree with it by selecting the appropriate option.",
      questions: [
        {
          id: "Q1",
          text: "I tend to bounce back quickly after hard times.",
          responseType: "select",
          options: [
            { value: 1, label: "Strongly disagree" },
            { value: 2, label: "Disagree" },
            { value: 3, label: "Neutral" },
            { value: 4, label: "Agree" },
            { value: 5, label: "Strongly agree" },
          ],
        },
        {
          id: "Q2",
          text: "I have a hard time making it through stressful events.",
          responseType: "select",
          options: [
            { value: 1, label: "Strongly disagree" },
            { value: 2, label: "Disagree" },
            { value: 3, label: "Neutral" },
            { value: 4, label: "Agree" },
            { value: 5, label: "Strongly agree" },
          ],
        },
        {
          id: "Q3",
          text: "It does not take me long to recover from a stressful event.",
          responseType: "select",
          options: [
            { value: 1, label: "Strongly disagree" },
            { value: 2, label: "Disagree" },
            { value: 3, label: "Neutral" },
            { value: 4, label: "Agree" },
            { value: 5, label: "Strongly agree" },
          ],
        },
        {
          id: "Q4",
          text: "It is hard for me to snap back when something bad happens.",
          responseType: "select",
          options: [
            { value: 1, label: "Strongly disagree" },
            { value: 2, label: "Disagree" },
            { value: 3, label: "Neutral" },
            { value: 4, label: "Agree" },
            { value: 5, label: "Strongly agree" },
          ],
        },
        {
          id: "Q5",
          text: "I usually come through difficult times with little trouble.",
          responseType: "select",
          options: [
            { value: 1, label: "Strongly disagree" },
            { value: 2, label: "Disagree" },
            { value: 3, label: "Neutral" },
            { value: 4, label: "Agree" },
            { value: 5, label: "Strongly agree" },
          ],
        },
        {
          id: "Q6",
          text: "I tend to take a long time to get over set-backs in my life.",
          responseType: "select",
          options: [
            { value: 1, label: "Strongly disagree" },
            { value: 2, label: "Disagree" },
            { value: 3, label: "Neutral" },
            { value: 4, label: "Agree" },
            { value: 5, label: "Strongly agree" },
          ],
        },
      ],
    },
    {
      instructions:
        "Over the last two weeks, for each of the following statements, please indicate how often it applied to you.",
      questions: [
        {
          id: "Q7",
          text: "Over the last two weeks, I have felt cheerful and in good spirits.",
          responseType: "select",
          options: [
            { value: 0, label: "At no time" },
            { value: 1, label: "Some of the time" },
            { value: 2, label: "Less than half of the time" },
            { value: 3, label: "More than half of the time" },
            { value: 4, label: "Most of the time" },
            { value: 5, label: "All of the time" },
          ],
        },
        {
          id: "Q8",
          text: "Over the last two weeks, I have felt calm and relaxed.",
          responseType: "select",
          options: [
            { value: 0, label: "At no time" },
            { value: 1, label: "Some of the time" },
            { value: 2, label: "Less than half of the time" },
            { value: 3, label: "More than half of the time" },
            { value: 4, label: "Most of the time" },
            { value: 5, label: "All of the time" },
          ],
        },
        {
          id: "Q9",
          text: "Over the last two weeks, I have felt active and vigorous.",
          responseType: "select",
          options: [
            { value: 0, label: "At no time" },
            { value: 1, label: "Some of the time" },
            { value: 2, label: "Less than half of the time" },
            { value: 3, label: "More than half of the time" },
            { value: 4, label: "Most of the time" },
            { value: 5, label: "All of the time" },
          ],
        },
        {
          id: "Q10",
          text: "Over the last two weeks, I woke up feeling fresh and rested.",
          responseType: "select",
          options: [
            { value: 0, label: "At no time" },
            { value: 1, label: "Some of the time" },
            { value: 2, label: "Less than half of the time" },
            { value: 3, label: "More than half of the time" },
            { value: 4, label: "Most of the time" },
            { value: 5, label: "All of the time" },
          ],
        },
        {
          id: "Q11",
          text: "Over the last two weeks, my daily life has been filled with things that interest me.",
          responseType: "select",
          options: [
            { value: 0, label: "At no time" },
            { value: 1, label: "Some of the time" },
            { value: 2, label: "Less than half of the time" },
            { value: 3, label: "More than half of the time" },
            { value: 4, label: "Most of the time" },
            { value: 5, label: "All of the time" },
          ],
        },
      ],
    },
    {
      instructions:
        "For each statement, please indicate the frequency with which you experience it at work, using the following scale.",
      questions: [
        {
          id: "Q12",
          text: "At my work, I feel bursting with energy.",
          responseType: "select",
          options: [
            { value: 0, label: "Never" },
            { value: 1, label: "Almost never" },
            { value: 2, label: "Rarely" },
            { value: 3, label: "Sometimes" },
            { value: 4, label: "Often" },
            { value: 5, label: "Very often" },
            { value: 6, label: "Always/every day" },
          ],
        },
        {
          id: "Q13",
          text: "At my job, I feel strong and vigorous.",
          responseType: "select",
          options: [
            { value: 0, label: "Never" },
            { value: 1, label: "Almost never" },
            { value: 2, label: "Rarely" },
            { value: 3, label: "Sometimes" },
            { value: 4, label: "Often" },
            { value: 5, label: "Very often" },
            { value: 6, label: "Always/every day" },
          ],
        },
        {
          id: "Q14",
          text: "I am enthusiastic about my job.",
          responseType: "select",
          options: [
            { value: 0, label: "Never" },
            { value: 1, label: "Almost never" },
            { value: 2, label: "Rarely" },
            { value: 3, label: "Sometimes" },
            { value: 4, label: "Often" },
            { value: 5, label: "Very often" },
            { value: 6, label: "Always/every day" },
          ],
        },
        {
          id: "Q15",
          text: "My job inspires me.",
          responseType: "select",
          options: [
            { value: 0, label: "Never" },
            { value: 1, label: "Almost never" },
            { value: 2, label: "Rarely" },
            { value: 3, label: "Sometimes" },
            { value: 4, label: "Often" },
            { value: 5, label: "Very often" },
            { value: 6, label: "Always/every day" },
          ],
        },
        {
          id: "Q16",
          text: "When I get up in the morning, I feel like going to work.",
          responseType: "select",
          options: [
            { value: 0, label: "Never" },
            { value: 1, label: "Almost never" },
            { value: 2, label: "Rarely" },
            { value: 3, label: "Sometimes" },
            { value: 4, label: "Often" },
            { value: 5, label: "Very often" },
            { value: 6, label: "Always/every day" },
          ],
        },
        {
          id: "Q17",
          text: "I feel happy when I am working intensely.",
          responseType: "select",
          options: [
            { value: 0, label: "Never" },
            { value: 1, label: "Almost never" },
            { value: 2, label: "Rarely" },
            { value: 3, label: "Sometimes" },
            { value: 4, label: "Often" },
            { value: 5, label: "Very often" },
            { value: 6, label: "Always/every day" },
          ],
        },
        {
          id: "Q18",
          text: "I am proud of the work that I do.",
          responseType: "select",
          options: [
            { value: 0, label: "Never" },
            { value: 1, label: "Almost never" },
            { value: 2, label: "Rarely" },
            { value: 3, label: "Sometimes" },
            { value: 4, label: "Often" },
            { value: 5, label: "Very often" },
            { value: 6, label: "Always/every day" },
          ],
        },
        {
          id: "Q19",
          text: "I am immersed in my work.",
          responseType: "select",
          options: [
            { value: 0, label: "Never" },
            { value: 1, label: "Almost never" },
            { value: 2, label: "Rarely" },
            { value: 3, label: "Sometimes" },
            { value: 4, label: "Often" },
            { value: 5, label: "Very often" },
            { value: 6, label: "Always/every day" },
          ],
        },
        {
          id: "Q20",
          text: "I get carried away when I’m working.",
          responseType: "select",
          options: [
            { value: 0, label: "Never" },
            { value: 1, label: "Almost never" },
            { value: 2, label: "Rarely" },
            { value: 3, label: "Sometimes" },
            { value: 4, label: "Often" },
            { value: 5, label: "Very often" },
            { value: 6, label: "Always/every day" },
          ],
        },
      ],
    },
    {
      instructions: "Post-intervention interview",
      questions: [
        {
          id: "A1",
          text: "Would you like to be contacted via email for participation in a follow-up interview?",
          responseType: "select",
          options: [
            { value: 1, label: "Yes" },
            { value: 0, label: "No" },
          ],
        },
      ],
    },
  ],
};
